modLoader = "javafml"
loaderVersion = "${forge_version_range}"
license = "${license}"
issueTrackerURL = "${issue_tracker}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${homepage}"
logoFile = "${icon}"
authors = "${mod_author}"
description = '''${description}'''

[[dependencies.fossilslegacy]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.fossilslegacy]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
