modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/willatendo/Extra-Item-Uses/issues"

[[mods]]
modId="extraitemuses"
version="1.0.0"
displayName="Extra Item Uses" 
updateJSONURL=""
displayURL="https://modrinth.com/mod/extra-item-uses"
logoFile="extra_item_uses_icon.png"
authors="Willatendo"
description='''
Adds new functions to items!
'''

[[dependencies.extraitemuses]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.extraitemuses]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.extraitemuses]]
    modId="simplelibrary"
    mandatory=true
    versionRange="[1.0.5,1.1.0)"
    ordering="NONE"
    side="BOTH"
    