modLoader="javafml"
loaderVersion="[45,)"
license="https://github.com/willatendo/Willatendos-Licensing"
issueTrackerURL="https://github.com/willatendo/More-Right-Click-Functions/issues"

[[mods]]
modId="extraitemuses" 
version="3.0.0"
displayName="Extra Item Uses"
updateJSONURL="https://github.com/willatendo/More-Right-Click-Functions/raw/main/updates.json"
displayURL="https://github.com/willatendo/More-Right-Click-Functions"
logoFile="extra_item_uses.png" 
authors="Willatendo"
description='''
Adds more right click functions!
'''

[[dependencies.extraitemuses]] 
    modId="forge" 
    mandatory=true 
    versionRange="[45,)" 
    ordering="NONE"
    side="BOTH"
    
[[dependencies.extraitemuses]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"