modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
# issueTrackerURL=""

[[mods]]
modId="morerightclickfunctions" 
version="1.0.0"
displayName="More Right Click Functions"
# updateJSONURL=""
# displayURL=""
# logoFile="" 
authors="Willatendo"
description='''
Adds more right click functions!
'''

[[dependencies.morerightclickfunctions]] 
    modId="forge" 
    mandatory=true 
    versionRange="[39,)" 
    ordering="NONE"
    side="BOTH"
    
[[dependencies.morerightclickfunctions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.roses]]
    modId="morerightclickfunctions"
    mandatory=true
    versionRange="[v4.0.0,)"
    ordering="NONE"
    side="BOTH"