modLoader = "javafml"
loaderVersion = "${neoforge_version_range}"
license = "${license}"
issueTrackerURL = "${issue_tracker}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${homepage}"
logoFile = "${icon}"
authors = "${mod_author}"
description = '''${description}'''

[[dependencies.fossilslegacy]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.fossilslegacy]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"